# ChronoRetrace 水平Pod自动扩缩器配置
# Horizontal Pod Autoscaler (HPA) 配置

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chronoretrace-backend-hpa
  namespace: chronoretrace
  labels:
    app: chronoretrace
    component: backend
    tier: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chronoretrace-backend
  
  # 扩缩容范围
  minReplicas: 2
  maxReplicas: 10
  
  # 扩缩容指标
  metrics:
  # CPU使用率指标
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # 内存使用率指标
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # 自定义指标：请求速率
  - type: Pods
    pods:
      metric:
        name: requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  
  # 自定义指标：响应时间
  - type: Pods
    pods:
      metric:
        name: response_time_ms
      target:
        type: AverageValue
        averageValue: "500"
  
  # 扩缩容行为配置
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 缩容稳定窗口5分钟
      policies:
      - type: Percent
        value: 50  # 每次最多缩容50%
        periodSeconds: 60
      - type: Pods
        value: 2   # 每次最多缩容2个Pod
        periodSeconds: 60
      selectPolicy: Min  # 选择最保守的策略
    
    scaleUp:
      stabilizationWindowSeconds: 60   # 扩容稳定窗口1分钟
      policies:
      - type: Percent
        value: 100  # 每次最多扩容100%
        periodSeconds: 60
      - type: Pods
        value: 4    # 每次最多扩容4个Pod
        periodSeconds: 60
      selectPolicy: Max  # 选择最激进的策略

---
# 前端应用HPA配置
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chronoretrace-frontend-hpa
  namespace: chronoretrace
  labels:
    app: chronoretrace
    component: frontend
    tier: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chronoretrace-frontend
  
  minReplicas: 2
  maxReplicas: 6
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60

---
# Redis HPA配置
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chronoretrace-redis-hpa
  namespace: chronoretrace
  labels:
    app: chronoretrace
    component: redis
    tier: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chronoretrace-redis
  
  minReplicas: 1
  maxReplicas: 3
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  
  # Redis特定指标
  - type: Pods
    pods:
      metric:
        name: redis_connected_clients
      target:
        type: AverageValue
        averageValue: "100"
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Redis缩容更保守
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
    
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60

---
# 工作节点HPA配置（用于后台任务）
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chronoretrace-worker-hpa
  namespace: chronoretrace
  labels:
    app: chronoretrace
    component: worker
    tier: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chronoretrace-worker
  
  minReplicas: 1
  maxReplicas: 5
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  
  # 队列长度指标
  - type: External
    external:
      metric:
        name: redis_queue_length
        selector:
          matchLabels:
            queue: "data_processing"
      target:
        type: AverageValue
        averageValue: "10"
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
    
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60