# Type stubs for SQLAlchemy models
from typing import Optional
from datetime import datetime, date
from sqlalchemy.ext.declarative import DeclarativeMeta

class Base(metaclass=DeclarativeMeta): ...

class StockData(Base):
    __tablename__: str
    id: int
    ts_code: str
    trade_date: date
    open: Optional[float]
    high: Optional[float]
    low: Optional[float]
    close: Optional[float]
    pre_close: Optional[float]
    change: Optional[float]
    pct_chg: Optional[float]
    vol: Optional[float]
    amount: Optional[float]
    interval: str

class StockInfo(Base):
    __tablename__: str
    ts_code: str
    name: str
    market_type: str
    last_updated: datetime

class DailyStockMetrics(Base):
    __tablename__: str
    id: int
    code: str
    date: date
    market: str
    close_price: Optional[float]
    pe_ratio: Optional[float]
    pb_ratio: Optional[float]
    market_cap: Optional[int]
    dividend_yield: Optional[float]
    ma5: Optional[float]
    ma20: Optional[float]
    volume: Optional[int]
    updated_at: datetime

class AnnualEarnings(Base):
    __tablename__: str
    id: int
    ts_code: str
    ann_date: date
    f_ann_date: date
    end_date: date
    eps: Optional[float]
    dt_eps: Optional[float]
    total_revenue_ps: Optional[float]
    revenue_ps: Optional[float]
    capital_rese_ps: Optional[float]
    surplus_rese_ps: Optional[float]
    undist_profit_ps: Optional[float]
    extra_item: Optional[float]
    profit_dedt: Optional[float]
    gross_margin: Optional[float]
    current_ratio: Optional[float]
    quick_ratio: Optional[float]
    cash_ratio: Optional[float]
    invturn_days: Optional[float]
    arturn_days: Optional[float]
    inv_turn: Optional[float]
    ar_turn: Optional[float]
    ca_turn: Optional[float]
    fa_turn: Optional[float]
    assets_turn: Optional[float]
    op_income: Optional[float]
    valuechange_income: Optional[float]
    interst_income: Optional[float]
    daa: Optional[float]
    ebit: Optional[float]
    ebitda: Optional[float]
    fcff: Optional[float]
    fcfe: Optional[float]
    current_exint: Optional[float]
    noncurrent_exint: Optional[float]
    interestdebt: Optional[float]
    netdebt: Optional[float]
    tangible_asset: Optional[float]
    working_capital: Optional[float]
    networking_capital: Optional[float]
    invest_capital: Optional[float]
    retained_earnings: Optional[float]
    diluted2_eps: Optional[float]
    bps: Optional[float]
    ocfps: Optional[float]
    retainedps: Optional[float]
    cfps: Optional[float]
    ebit_ps: Optional[float]
    fcff_ps: Optional[float]
    fcfe_ps: Optional[float]
    netprofit_margin: Optional[float]
    grossprofit_margin: Optional[float]
    cogs_of_sales: Optional[float]
    expense_of_sales: Optional[float]
    profit_to_gr: Optional[float]
    saleexp_to_gr: Optional[float]
    adminexp_of_gr: Optional[float]
    finaexp_of_gr: Optional[float]
    impai_ttm: Optional[float]
    gc_of_gr: Optional[float]
    op_of_gr: Optional[float]
    ebit_of_gr: Optional[float]
    roe: Optional[float]
    roe_waa: Optional[float]
    roe_dt: Optional[float]
    roa: Optional[float]
    npta: Optional[float]
    roic: Optional[float]
    roe_yearly: Optional[float]
    roa2_yearly: Optional[float]
    roe_avg: Optional[float]
    opincome_of_ebt: Optional[float]
    investincome_of_ebt: Optional[float]
    n_op_profit_of_ebt: Optional[float]
    tax_to_ebt: Optional[float]
    dtprofit_to_profit: Optional[float]
    salescash_to_or: Optional[float]
    ocf_to_or: Optional[float]
    ocf_to_opincome: Optional[float]
    capitalized_to_da: Optional[float]
    debt_to_assets: Optional[float]
    assets_to_eqt: Optional[float]
    dp_assets_to_eqt: Optional[float]
    ca_to_assets: Optional[float]
    nca_to_assets: Optional[float]
    tbassets_to_totalassets: Optional[float]
    int_to_talcap: Optional[float]
    eqt_to_talcapital: Optional[float]
    currentdebt_to_debt: Optional[float]
    longdeb_to_debt: Optional[float]
    ocf_to_shortdebt: Optional[float]
    debt_to_eqt: Optional[float]
    eqt_to_debt: Optional[float]
    eqt_to_interestdebt: Optional[float]
    tangibleasset_to_debt: Optional[float]
    tangasset_to_intdebt: Optional[float]
    tangibleasset_to_netdebt: Optional[float]
    ocf_to_debt: Optional[float]
    ocf_to_interestdebt: Optional[float]
    ocf_to_netdebt: Optional[float]
    ebit_to_interest: Optional[float]
    longdebt_to_workingcapital: Optional[float]
    ebitda_to_debt: Optional[float]
    turn_days: Optional[float]
    roa_yearly: Optional[float]
    roa_dp: Optional[float]
    fixed_assets: Optional[float]
    profit_prefin_exp: Optional[float]
    non_op_profit: Optional[float]
    op_profit: Optional[float]
    ebit_ebitda: Optional[float]
    profit_to_op: Optional[float]
    q_opincome: Optional[float]
    q_investincome: Optional[float]
    q_dtprofit: Optional[float]
    q_eps: Optional[float]
    q_netprofit_margin: Optional[float]
    q_gsprofit_margin: Optional[float]
    q_exp_to_sales: Optional[float]
    q_profit_to_gr: Optional[float]
    q_saleexp_to_gr: Optional[float]
    q_adminexp_to_gr: Optional[float]
    q_finaexp_to_gr: Optional[float]
    q_impair_to_gr_ttm: Optional[float]
    q_gc_to_gr: Optional[float]
    q_op_to_gr: Optional[float]
    q_roe: Optional[float]
    q_dt_roe: Optional[float]
    q_npta: Optional[float]
    q_opincome_to_ebt: Optional[float]
    q_investincome_to_ebt: Optional[float]
    q_dtprofit_to_profit: Optional[float]
    q_salescash_to_or: Optional[float]
    q_ocf_to_sales: Optional[float]
    q_ocf_to_or: Optional[float]
    basic_eps_yoy: Optional[float]
    dt_eps_yoy: Optional[float]
    cfps_yoy: Optional[float]
    op_yoy: Optional[float]
    ebt_yoy: Optional[float]
    netprofit_yoy: Optional[float]
    dt_netprofit_yoy: Optional[float]
    ocf_yoy: Optional[float]
    roe_yoy: Optional[float]
    bps_yoy: Optional[float]
    assets_yoy: Optional[float]
    eqt_yoy: Optional[float]
    tr_yoy: Optional[float]
    or_yoy: Optional[float]
    q_gr_yoy: Optional[float]
    q_gr_qoq: Optional[float]
    q_sales_yoy: Optional[float]
    q_sales_qoq: Optional[float]
    q_op_yoy: Optional[float]
    q_op_qoq: Optional[float]
    q_profit_yoy: Optional[float]
    q_profit_qoq: Optional[float]
    q_netprofit_yoy: Optional[float]
    q_netprofit_qoq: Optional[float]
    equity_yoy: Optional[float]
    rd_exp: Optional[float]
    update_flag: Optional[str]

class CorporateAction(Base):
    __tablename__: str
    id: int
    ts_code: str
    ann_date: date
    record_date: Optional[date]
    ex_date: Optional[date]
    pay_date: Optional[date]
    div_proc: Optional[str]
    stk_div: Optional[float]
    stk_bo_rate: Optional[float]
    stk_co_rate: Optional[float]
    cash_div: Optional[float]
    cash_div_tax: Optional[float]
    record_date_desc: Optional[str]
    ex_date_desc: Optional[str]
    pay_date_desc: Optional[str]
    base_date: Optional[date]
    base_share: Optional[float]

class FundamentalData(Base):
    __tablename__: str
    id: int
    ts_code: str
    trade_date: date
    pe_ratio: Optional[float]
    pb_ratio: Optional[float]
    market_cap: Optional[float]
    total_share: Optional[float]
    float_share: Optional[float]
    free_share: Optional[float]
    turnover_rate: Optional[float]
    turnover_rate_f: Optional[float]
    volume_ratio: Optional[float]
    pe_ttm: Optional[float]
    pb_mrq: Optional[float]
    ps_ttm: Optional[float]
    ps_mrq: Optional[float]
    dv_ratio: Optional[float]
    dv_ttm: Optional[float]
    total_mv: Optional[float]
    circ_mv: Optional[float]

class IndustryClassification(Base):
    __tablename__: str
    ts_code: str
    industry_code: str
    industry_name: str
    src: str
    level: str
    industry_code_new: Optional[str]
    industry_name_new: Optional[str]