repos:
-   repo: local
    hooks:
    -   id: pytest-backend
        name: pytest-backend
        entry: poetry run pytest backend/
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
