repos:
-   repo: local
    hooks:
    -   id: pytest-backend
        name: pytest-backend
        entry: pytest backend/
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        additional_dependencies:
        -   -r backend/requirements.txt
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        stages: [pre-push]
