# .pre-commit-config.yaml
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
        # Run the linter.
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]
        # Run the formatter.
        - id: ruff-format
